stages:
  - build
  - test
  - deploy

build:
  stage: build
  script:
    - powershell -ExecutionPolicy Bypass -File .\remove_containers_and_images.ps1
    - docker system prune -a -f
    - docker compose up -d
  only:
    - project
  tags:
    - local

test:
  stage: test
  before_script:
    # - docker compose up -d
  after_script:
    - docker compose down
  script:
    - powershell -ExecutionPolicy Bypass -File .\tests\containers\check_containers.ps1
  only:
    - project
  tags:
    - local

deploy:
  stage: deploy
  script:
    - docker compose up -d
  only:
    - project
  tags:
    - local
