stages:
  - build
  - test
  - deploy

build:
  stage: build
  script:
    - npm install
  only:
    - project

test:
  stage: test
  script:
    - echo "Running tests..."
  only:
    - project

deploy:
  stage: deploy
  script:
    - echo "Running deploy..."
  only:
    - project
