stages:
  - build
  - test
  - deploy

build:
  stage: build
  script:
    - docker stop $(docker ps -a -q) 
    - docker rm $(docker ps -a -q)
    - docker rmi $(docker images -q)
    - docker system prune -a -f
    - docker compose build
  only:
    - project
  tags:
    - local

test:
  stage: test
  before_script:
    - docker compose up -d
  after_script:
    - docker compose down
  script:
    - powershell -ExecutionPolicy Bypass -File .\tests\containers\check_containers.ps1
  only:
    - project
  tags:
    - local

deploy:
  stage: deploy
  script:
    - docker compose up -d
  only:
    - project
  tags:
    - local
