stages:
  - build
  - test
  - deploy

build:
  stage: build
  script:
    - powershell -ExecutionPolicy Bypass -File .\scripts\remove_containers_and_images.ps1
    - docker system prune -a -f
    - docker compose build
  only:
    - project
  tags:
    - local

test:
  stage: test
  before_script:
    - docker compose up -d
  after_script:
    - docker compose down
  script:
    - powershell -ExecutionPolicy Bypass -File .\tests\containers\check_containers.ps1
    - echo "test services are up and running"
    - npx newman run .\tests\DevopsProject.postman_collection.json
    - powershell -ExecutionPolicy Bypass -File .\tests\containers\check_containers_shutdown.ps1

  only:
    - project
  tags:
    - local

deploy:
  stage: deploy
  script:
    - docker compose up -d
  only:
    - project
  tags:
    - local
